### ISSUE TITLE
Error while accessing https://ec.europa.eu/info/law/better-regulation/brpapi/allFeedback?publicationId=24212003&page=0 - status code: [404]""

### ISSUE THREAD

**Issue by lululililu** [FelixRech/hys_scraper#4]
Dear Felix, 

I am struggling to use your tool while I had no issues before. This message appears now 

"Scraping the feedback:       [⏳]Traceback (most recent call last):
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\__main__.py", line 56, in <module>
    main()
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\__main__.py", line 52, in main
    HYS_Scraper(args.publication_id, **kwargs).scrape()
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 87, in scrape
    feedbacks_df = self.scrape_feedbacks()
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 132, in scrape_feedbacks
    feedbacks = self._scrape_pages()
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 170, in _scrape_pages
    initial = self._scrape_page()
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 155, in _scrape_page
    r = self._get(url)
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 371, in _get
    return self._get(url, retries=retries - 1)
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 371, in _get
    return self._get(url, retries=retries - 1)
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 371, in _get
    return self._get(url, retries=retries - 1)
  File "C:\Users\TE\AppData\Local\Programs\Python\Python39\lib\site-packages\hys_scraper\hys_scraper.py", line 372, in _get
    raise RuntimeError(
RuntimeError:
Error while accessing https://ec.europa.eu/info/law/better-regulation/brpapi/allFeedback?publicationId=24212003&page=0 - status code: [404]""

Apologies for the lack of feedback, but I am a complete noob when it comes to programming and to Github, sorry about the form of the message. 

Thanks a lot for the amazing scrapper !

**Comment by felixrech** [comment]
Sorry for the delay, I was pretty busy and this project just isn't my priority right now. Anyways, HYS made some minor changes to their API which caused the errors you observed. I modified the scraper accordingly and everything should work again now. You can update your installation of the scraper with `pip install -U hys_scraper` (or the equivalent for your installation method). If your errors persist or reoccur just (re)open (this) issue.

**Comment by lululililu** [comment]
Hey Felix,

Super cool, thanks a lot. Really makes it easier to analyze the content of
the submissions, I love it!

Have a nice day and thanks again,
Elias
